version: "3.9"
services:
  ipfs:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
      # - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      # - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
      - ./ipfs_add_files:/export
      # - ipfs_staging:/export

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - ./client:/app/client

    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    command: python /app/api/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
