version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./client:/app/client

    depends_on:
      - api

  api:
    build:
      context: ./api 
      dockerfile: Dockerfile

    command: python /app/api/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - 8000:8000
    depends_on:
      - db 

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
