# Generated by Django 4.1.7 on 2023-03-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('eventcompetitors', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='events',
            field=models.ManyToManyField(through='eventcompetitors.EventCompetitor', to='events.event'),
        ),
    ]
